Create movie details screen
VitaliiDiadchenko/MyKotkinApplication pull request #1
Opened 2020-11-17 16:01 UTC by VitaliiDiadchenko

Create movie detail screen
Add fun moveToDetail in Main Activity
Change .gitignore file

2020-11-19 13:20 UTC, an-yurii requested changes
Нужно сделать плоскую верстку

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">@dimen/text_size_button_path_to_back</item>
Размер шрифта можно было оставить константой. Выносить его в переменную - излишнее усложнение. Ты уже выделил стиль начертания и этого достаточно.

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/values/styles.xml
> +    <style name="back_to_path">
Гугл предлагает соглашение об именовании стилей
https://material.io/develop/android/theming/typography
https://habr.com/ru/company/redmadrobot/blog/461201/ (статья от RadMadRobot)

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/values/styles.xml
> +    <style name="movie_title_style">
Именовать стили нужно не по месту применения, а по назначению. Например, `<...>.Header1`

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/values/colors.xml
> +    <color name="text_movie_title">#ECECEC</color>
Выбор названий цветов в палитре - сложная задача)
Хорошая статья по теме https://habr.com/ru/company/redmadrobot/blog/523916/

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout-land/activity_movie_detail.xml
> +        <FrameLayout
Нужно избегать вложенных конструкций в верстке. Это - причина проблем отрисовки. ConsraintLayout был создан для того, чтобы делать плоскую верстку.
Нужно убрать `FrameLayout`

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout-land/activity_movie_detail.xml
> +                app:layout_constraintTop_toTopOf="@+id/frameTitleImage" />
Родительским контейнером данного элемента является FrameLayout, связи ConstraintLayout для него не работают.
Чтобы наложить тень поверх картинки, ты можешь привязать границы `view_gradient` к `image_poster` (верх к верху, низ к низу и т.д.)

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +                android:layout_height="@dimen/poster_height"
Заменить на `wrap_content`

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +                app:layout_constraintTop_toTopOf="@+id/frameTitleImage" />
Родительским контейнером данного элемента является FrameLayout, связи ConstraintLayout для него не работают.
Чтобы наложить тень поверх картинки, ты можешь привязать границы view_gradient к image_poster (верх к верху, низ к низу и т.д.)

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +        <FrameLayout
Нужно избегать вложенных конструкций в верстке. Это - причина проблем отрисовки. ConsraintLayout был создан для того, чтобы делать плоскую верстку.
Нужно убрать FrameLayout

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +            app:srcCompat="@drawable/img_path_to_back" />
Есть соглашение об именовании иконок: имя начинается с `ic_`.
Формат `webp` используется для растровых картинок. Иконки нужно экспортировать из `svg`

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +            app:layout_constraintStart_toEndOf="@+id/image_path_to_back"
Стрелка отдельным элементом не нужна. Достаточно добавить параметр `app:drawableLeftCompat="@drawable/img_path_to_back"`

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +        <TextView
Обрати внимание: как этот элемент сверстан в фигме. Это - кликабельный элемент.
![image](https://user-images.githubusercontent.com/31529762/99669969-63a8af80-2aa2-11eb-89d9-4bbc3f109001.png)

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +        <FrameLayout
Тоже лишний контейнер.

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +            android:layout_marginTop="222dp"
Отступ не нужен (это будет справедливо для `movieTitle`). 
Тебе нужно привязать заголовок к нижнему краю постера.
```
            app:layout_constraintTop_toBottomOf="@+id/image_poster"
            app:layout_constraintBottom_toBottomOf="@+id/image_poster"
```

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +                app:layout_constraintBottom_toBottomOf="@+id/backgroundAgeRating"
Внутри `FrameLayout` эти связи не работают. Когда избавишься от него, нужно будет привязать только левый край к экрану, а нижний - к `movieTitle`.

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +                android:layout_marginTop="@dimen/small_gap"
Как правило, верстка уникальна для каждого экрана. Поэтому не стоит выносить в переменные отступы между вьюхами. Имеет смысл выносить стандартные размеры, как, например, отступы слева и справа.

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +            android:layout_marginTop="6dp"
Чтобы выровнять элемент по высоте относительно `textReview`, нужно привязаться к нему: верх к верху, низ к низу.

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +            android:layout_marginStart="8.89dp"
Какой-то странный отступ)

2020-11-19 13:20 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +            style="@style/storyline_style"
Элементы, которые отображают текст имеют специальный атрибут для стилей начертания текста.
https://developer.android.com/reference/android/widget/TextView#attr_android:textAppearance

2020-11-19 21:17 UTC, VitaliiDiadchenko commented on app/src/main/res/layout/activity_movie_detail.xml
> +            style="@style/storyline_style"
В Figme такой отступ)

![Отступ 8,89](https://user-images.githubusercontent.com/70446113/99725131-b21b7580-2ac5-11eb-8e8f-ed46ec3dfbc1.png)

2020-11-19 21:20 UTC, VitaliiDiadchenko commented on app/src/main/res/layout/activity_movie_detail.xml
> +            android:layout_marginStart="8.89dp"
В Figme такой отступ)

![Отступ 8,89](https://user-images.githubusercontent.com/70446113/99725376-18a09380-2ac6-11eb-9e39-8242ae9b877f.png)

2020-11-20 02:13 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +            android:layout_marginStart="8.89dp"
Извини, грубоватый комментарий получился. Гугл рекомендует, чтобы все размеры были кратны 8. Отступы могут быть меньше, но кратны 2. В данном случае, нужно оставить 8.
Вообще говоря, дизайн - боль. Часто, дизайнеры верстают под iOS с ее требованиями, под андроид специально не верстают. Вторая сторона, часто у дизайнеров отсутствует готовый набор компонентов. Делают по принципу "я художник, я так вижу". Разрабам приходится чекать макеты и договариваться с дизайнерами.

2020-11-21 10:14 UTC, an-yurii commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_height">wrap_content</item>
Не стоит смешивать стиль начертания текста с внешним видом вьюхи. Эти параметры нужно бы оставить непосредственно в макете страницы.

2020-11-21 10:28 UTC, an-yurii approved these changes

2020-11-21 10:28 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +            android:id="@+id/backgroundAgeRating"
В первый раз я пропустил. Этот элемент не нужен в верстке Андроид.

2020-11-21 10:28 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_detail.xml
> +            app:layout_constraintBottom_toBottomOf="@+id/backgroundAgeRating"
Нужно привязать к заголовку и добавить вертикальный padding

2020-11-21 16:27 UTC, merged